#!/usr/bin/env python3
"""Convert the 15 photo variants into 128x128 RGB565 Arduino arrays."""

from pathlib import Path
import struct
import subprocess


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/display/family_photos_rgb565.h"

PHOTOS = (
    ("cabin", "CABIN", False),
    ("momandbro", "MOM_AND_BRO", False),
    ("momanddad", "MOM_AND_DAD", True),
    ("mom", "MOM", False),
    ("three", "THREE", False),
)
LEVELS = (
    ("night", "NIGHT"),
    ("sunrise", "SUNRISE"),
    ("midday", "MIDDAY"),
)


def rgb565_pixels(path: Path, rotate_180: bool) -> tuple[int, ...]:
    filters = []
    if rotate_180:
        filters.append("hflip,vflip")
    filters.extend((
        "scale=128:128:force_original_aspect_ratio=decrease:flags=lanczos",
        "pad=128:128:(ow-iw)/2:(oh-ih)/2:black",
    ))

    result = subprocess.run(
        (
            "ffmpeg", "-loglevel", "error", "-i", str(path),
            "-vf", ",".join(filters),
            "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", "rgb565le", "-",
        ),
        check=True,
        stdout=subprocess.PIPE,
    )
    expected_bytes = 128 * 128 * 2
    if len(result.stdout) != expected_bytes:
        raise RuntimeError(
            f"{path.name}: expected {expected_bytes} RGB565 bytes, got {len(result.stdout)}"
        )
    return struct.unpack("<16384H", result.stdout)


def format_array(source: Path, array_name: str, pixels: tuple[int, ...]) -> str:
    lines = [
        f"// Source: {source.name}",
        f"constexpr uint16_t {array_name}[] PROGMEM = {{",
    ]
    for start in range(0, len(pixels), 12):
        values = ", ".join(f"0x{pixel:04X}" for pixel in pixels[start:start + 12])
        lines.append(f"  {values},")
    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> None:
    sections = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Full-color RGB565 renderings, proportionally scaled to fit 128x128 without cropping.",
        "// Generated by tools/generate_photo_header.py; do not edit the pixel arrays by hand.",
        "",
    ]

    for base_name, symbol, rotate_180 in PHOTOS:
        for level_name, level_symbol in LEVELS:
            source = ROOT / f"{base_name}_{level_name}.png"
            if not source.exists():
                raise FileNotFoundError(f"Missing required photo variant: {source}")
            pixels = rgb565_pixels(source, rotate_180)
            sections.append(
                format_array(source, f"{symbol}_{level_symbol}_PHOTO_RGB565", pixels)
            )

    temporary = OUTPUT.with_suffix(".h.tmp")
    temporary.write_text("\n".join(sections), encoding="utf-8")
    temporary.replace(OUTPUT)
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
